title: OsaruEdiae
github_username: Edidevi
url: https://edidevi.github.io/Expression-V1/

nav:
  - label: About
    url: https://edidevi.github.io/About/
  - label: Linkedin
    url: https://www.linkedin.com/in/osaru-e-4011a7192/
  - label: Networking
    url: https://edidevi.github.io/My-Work/
  - label: Blog
    url: 

footer:
  hosted_on: GitHub Pages
  hosted_url: https://pages.github.com

defaults:
  - scope:
      path: ""
    values:
      layout: "expression"
